### ISSUE TITLE
[Enhancement] show list of buffers only in the command line

### ISSUE THREAD

**Issue by jmlucjav** [bling/vim-bufferline#9]
I am using
        let g:bufferline_echo = 1
now, but I would like to have the buffer list just in the command bar, not also. Would it be possible?

**Comment by wj-zhe** [comment]
@bling disabling integration with airline does help to solve the issue. Thx! BTW, don't know about others, but seems to me that showing buffers in command line should be the default w or w/o airline integration, since occupying same space in different buffer with same content just doesn't look good to me. Anyway, it's a very good and helpful plugin, love it, and thanks!
